# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.camera_view.setGeometry(QtCore.QRect(0, 0, 600, 401))
        self.camera_view.setObjectName("camera_view")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 400, 801, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.buttons_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttons_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.buttons_layout.setContentsMargins(10, 10, 10, 10)
        self.buttons_layout.setObjectName("buttons_layout")
        self.btn_settings = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy)
        self.btn_settings.setFlat(False)
        self.btn_settings.setObjectName("btn_settings")
        self.buttons_layout.addWidget(self.btn_settings)
        self.btn_instuction = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_instuction.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_instuction.sizePolicy().hasHeightForWidth())
        self.btn_instuction.setSizePolicy(sizePolicy)
        self.btn_instuction.setFlat(False)
        self.btn_instuction.setObjectName("btn_instuction")
        self.buttons_layout.addWidget(self.btn_instuction)
        self.btn_manual = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_manual.sizePolicy().hasHeightForWidth())
        self.btn_manual.setSizePolicy(sizePolicy)
        self.btn_manual.setFlat(False)
        self.btn_manual.setObjectName("btn_manual")
        self.buttons_layout.addWidget(self.btn_manual)
        self.btn_start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setFlat(False)
        self.btn_start.setObjectName("btn_start")
        self.buttons_layout.addWidget(self.btn_start)
        self.buttons_layout.setStretch(0, 10)
        self.buttons_layout.setStretch(1, 10)
        self.buttons_layout.setStretch(2, 10)
        self.buttons_layout.setStretch(3, 10)
        self.log_view = QtWidgets.QLabel(self.centralwidget)
        self.log_view.setGeometry(QtCore.QRect(600, 0, 201, 391))
        self.log_view.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.log_view.setObjectName("log_view")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_settings.setText(_translate("MainWindow", "Ułóż"))
        self.btn_instuction.setText(_translate("MainWindow", "Ręczne sterowanie"))
        self.btn_manual.setText(_translate("MainWindow", "Instrukcje"))
        self.btn_start.setText(_translate("MainWindow", "Ustawienia"))
        self.log_view.setText(_translate("MainWindow", "Logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
